version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

jobs:
  snapshot:
    docker:
      - image: buildkite/puppeteer:v1.15.0
    steps:
      - attach_workspace:
          at: .
      - run: npm install percy
      - run: PERCY_TOKEN=$PERCY_TOKEN npx percy snapshot ./public
  proofer:
    docker:
      - image: quay.io/hugoguru/html-proofer:3.19.2
    steps:
      - attach_workspace:
          at: .
      - run: html-proofer --external_only --check_html --url_ignore "/example.org/" ./public

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.88.1"
          html-proofer: false
      - proofer:
          requires:
            - hugo/build
      - snapshot:
          requires:
            - proofer