version: 2.1

parameters:
  external_only:
    type: boolean
    default: true
  check-html:
    type: boolean
    default: true
  url-ignore:
    type: string
    default: "/example.org/"

orbs:
  hugo: circleci/hugo@1.2.2

jobs:
  snapshot:
    docker:
      - image: buildkite/puppeteer:v1.15.0
    steps:
      - attach_workspace:
          at: .
      - run: npm install percy
      - run: PERCY_TOKEN=$PERCY_TOKEN npx percy snapshot ./public

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.88.1"
          html-proofer: true
      - snapshot:
          requires:
            - hugo/build