version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

jobs:
  snapshot:
    docker:
      - image: buildkite/puppeteer:v1.15.0
    steps:
      - run: htmlproofer --external_only --check_html --url_ignore "/example.org/" ./public
      - attach_workspace:
          at: .
      - run: npm install percy
      - run: PERCY_TOKEN=$PERCY_TOKEN npx percy snapshot ./public

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.88.1"
      - snapshot:
          requires:
            - hugo/build